# Generated by Django 3.2.7 on 2021-11-11 16:12

import contact.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=18, validators=[contact.models.validate_phone])),
                ('home_number', models.CharField(max_length=18, validators=[contact.models.validate_phone])),
                ('work_number', models.CharField(max_length=18, validators=[contact.models.validate_phone])),
                ('email_address', models.CharField(max_length=200, validators=[django.core.validators.EmailValidator])),
            ],
        ),
    ]
